-- Insert 50 popular movies with public poster URLs
INSERT INTO movies (title, release_year, director, short_description, trailer_url, poster, rating) VALUES
('The Shawshank Redemption', 1994, 'Frank Darabont', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'https://youtu.be/6hB3S9bIaco', 'https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg', 9.3),
('The Godfather', 1972, 'Francis Ford Coppola', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 'https://youtu.be/sY1S34973zA', 'https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg', 9.2),
('The Dark Knight', 2008, 'Christopher Nolan', 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.', 'https://youtu.be/EXeTwQWrcwY', 'https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg', 9.0),
('Pulp Fiction', 1994, 'Quentin Tarantino', 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'https://youtu.be/s7EdQ4FqbhY', 'https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg', 8.9),
('Fight Club', 1999, 'David Fincher', 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.', 'https://youtu.be/qtRKdVHc-cE', 'https://upload.wikimedia.org/wikipedia/en/f/fc/Fight_Club_poster.jpg', 8.8),
('Forrest Gump', 1994, 'Robert Zemeckis', 'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75.', 'https://youtu.be/bLvqoHBptjg', 'https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg', 8.8),
('Inception', 2010, 'Christopher Nolan', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.', 'https://youtu.be/YoHD9XEInc0', 'https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg', 8.8),
('The Matrix', 1999, 'Lana Wachowski, Lilly Wachowski', 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', 'https://youtu.be/vKQi3bBA1y8', 'https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg', 8.7),
('Goodfellas', 1990, 'Martin Scorsese', 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.', 'https://youtu.be/qo5jJpHtI1Y', 'https://upload.wikimedia.org/wikipedia/en/7/7b/Goodfellas.jpg', 8.7),
('The Silence of the Lambs', 1991, 'Jonathan Demme', 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.', 'https://youtu.be/W6Mm8Sbe__o', 'https://upload.wikimedia.org/wikipedia/en/8/86/The_Silence_of_the_Lambs_poster.jpg', 8.6),
('Parasite', 2019, 'Bong Joon Ho', 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.', 'https://youtu.be/5xH0HfJHsaY', 'https://upload.wikimedia.org/wikipedia/en/5/53/Parasite_%282019_film%29.png', 8.6),
('Interstellar', 2014, 'Christopher Nolan', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.', 'https://youtu.be/zSWdZVtXT7E', 'https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg', 8.6),
('The Lord of the Rings: The Fellowship of the Ring', 2001, 'Peter Jackson', 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.', 'https://youtu.be/V75dMMIW2B4', 'https://upload.wikimedia.org/wikipedia/en/8/8a/The_Lord_of_the_Rings_The_Fellowship_of_the_Ring_%282001%29.jpg', 8.8),
('The Lord of the Rings: The Return of the King', 2003, 'Peter Jackson', 'Gandalf and Aragorn lead the World of Men against Sauron''s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.', 'https://youtu.be/r5X-hFf6Bwo', 'https://upload.wikimedia.org/wikipedia/en/9/9d/Lord_of_the_Rings_-_The_Return_of_the_King.jpg', 8.9),
('The Green Mile', 1999, 'Frank Darabont', 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.', 'https://youtu.be/Ki4haFrqSrw', 'https://upload.wikimedia.org/wikipedia/en/c/ce/Green_mile.jpg', 8.6),
('Se7en', 1995, 'David Fincher', 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.', 'https://youtu.be/znmZoVkCjpI', 'https://upload.wikimedia.org/wikipedia/en/6/68/Seven_%28movie%29_poster.jpg', 8.6),
('The Usual Suspects', 1995, 'Bryan Singer', 'A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.', 'https://youtu.be/oiXdPolca5w', 'https://upload.wikimedia.org/wikipedia/en/9/9c/Usual_suspects_ver1.jpg', 8.5),
('Leon: The Professional', 1994, 'Luc Besson', 'Mathilda, a 12-year-old girl, is reluctantly taken in by Léon, a professional assassin, after her family is murdered. An unusual relationship forms as she becomes his protégée and learns the assassin''s trade.', 'https://youtu.be/jawVxq1Iyl0', 'https://upload.wikimedia.org/wikipedia/en/0/03/Leon-The_Professional.jpg', 8.5),
('Saving Private Ryan', 1998, 'Steven Spielberg', 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.', 'https://youtu.be/zwhP5b4tD6g', 'https://upload.wikimedia.org/wikipedia/en/a/ac/Saving_Private_Ryan_poster.jpg', 8.6),
('The Pianist', 2002, 'Roman Polanski', 'A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.', 'https://youtu.be/BFwGqLa_oAo', 'https://upload.wikimedia.org/wikipedia/en/4/4c/The_Pianist_movie.jpg', 8.5),
('Gladiator', 2000, 'Ridley Scott', 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.', 'https://youtu.be/uvbavW31adA', 'https://upload.wikimedia.org/wikipedia/en/8/8d/Gladiator_ver1.jpg', 8.5),
('The Departed', 2006, 'Martin Scorsese', 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.', 'https://youtu.be/iojhqm0JTW4', 'https://upload.wikimedia.org/wikipedia/en/5/50/Departed234.jpg', 8.5),
('The Prestige', 2006, 'Christopher Nolan', 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.', 'https://youtu.be/RLtaA9fFNXU', 'https://upload.wikimedia.org/wikipedia/en/d/d2/Prestige_poster.jpg', 8.5),
('Whiplash', 2014, 'Damien Chazelle', 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student''s potential.', 'https://youtu.be/7d_jQycdQGo', 'https://upload.wikimedia.org/wikipedia/en/0/01/Whiplash_poster.jpg', 8.5),
('Joker', 2019, 'Todd Phillips', 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.', 'https://youtu.be/zAGVQLHvwOY', 'https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg', 8.4),
('Django Unchained', 2012, 'Quentin Tarantino', 'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.', 'https://youtu.be/eUdM9vrCbow', 'https://upload.wikimedia.org/wikipedia/en/8/8b/Django_Unchained_Poster.jpg', 8.4),
('The Wolf of Wall Street', 2013, 'Martin Scorsese', 'Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.', 'https://youtu.be/iszwuX1AK6A', 'https://upload.wikimedia.org/wikipedia/en/1/1f/WallStreet2013poster.jpg', 8.2),
('Avengers: Infinity War', 2018, 'Anthony Russo, Joe Russo', 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.', 'https://youtu.be/6ZfuNTqbHE8', 'https://upload.wikimedia.org/wikipedia/en/4/4d/Avengers_Infinity_War_poster.jpg', 8.4),
('Avengers: Endgame', 2019, 'Anthony Russo, Joe Russo', 'After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos'' actions and restore balance to the universe.', 'https://youtu.be/TcMBFSGVi1c', 'https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg', 8.4),
('The Dark Knight Rises', 2012, 'Christopher Nolan', 'Eight years after the Joker''s reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.', 'https://youtu.be/GokKUqLcvD8', 'https://upload.wikimedia.org/wikipedia/en/8/83/Dark_knight_rises_poster.jpg', 8.4),
('Inglourious Basterds', 2009, 'Quentin Tarantino', 'In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner''s vengeful plans for the same.', 'https://youtu.be/KnrRy6kSzFU', 'https://upload.wikimedia.org/wikipedia/en/c/c3/Inglourious_Basterds_poster.jpg', 8.3),
('The Grand Budapest Hotel', 2014, 'Wes Anderson', 'The adventures of Gustave H, a legendary concierge at a famous hotel from the fictional Republic of Zubrowka between the first and second World Wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.', 'https://youtu.be/1Fg5iWmQjwk', 'https://upload.wikimedia.org/wikipedia/en/a/a6/The_Grand_Budapest_Hotel_Poster.jpg', 8.1),
('Spirited Away', 2001, 'Hayao Miyazaki', 'During her family''s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.', 'https://youtu.be/ByXuk9QqQkk', 'https://upload.wikimedia.org/wikipedia/en/d/db/Spirited_Away_Japanese_poster.png', 8.6),
('Your Name', 2016, 'Makoto Shinkai', 'Two teenagers share a profound, magical connection upon discovering they are swapping bodies. Things manage to become even more complicated when the boy and girl decide to meet in person.', 'https://youtu.be/xU47nhruN-Q', 'https://upload.wikimedia.org/wikipedia/en/0/0b/Your_Name_poster.png', 8.4),
('Coco', 2017, 'Lee Unkrich', 'Aspiring musician Miguel, confronted with his family''s ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.', 'https://youtu.be/Ga6RYejo6Hk', 'https://upload.wikimedia.org/wikipedia/en/9/98/Coco_%282017_film%29_poster.jpg', 8.4),
('The Lion King', 1994, 'Roger Allers, Rob Minkoff', 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.', 'https://youtu.be/4sj1MT05lAA', 'https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg', 8.5),
('Toy Story', 1995, 'John Lasseter', 'A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy''s room.', 'https://youtu.be/v-PjgYDrg70', 'https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg', 8.3),
('Toy Story 3', 2010, 'Lee Unkrich', 'The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it''s up to Woody to convince the other toys that they weren''t abandoned and to return home.', 'https://youtu.be/JcpWXaA2qeg', 'https://upload.wikimedia.org/wikipedia/en/6/69/Toy_Story_3_poster.jpg', 8.3),
('Up', 2009, 'Pete Docter', '78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway.', 'https://youtu.be/qas5lWp7_R0', 'https://upload.wikimedia.org/wikipedia/en/0/05/Up_%282009_film%29.jpg', 8.3),
('WALL·E', 2008, 'Andrew Stanton', 'In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.', 'https://youtu.be/CZ1CATNbXg0', 'https://upload.wikimedia.org/wikipedia/en/c/c2/WALL-Eposter.jpg', 8.4),
('Inside Out', 2015, 'Pete Docter', 'After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school.', 'https://youtu.be/seMwpP0yeu4', 'https://upload.wikimedia.org/wikipedia/en/0/0a/Inside_Out_%282015_film%29_poster.jpg', 8.2),
('The Incredibles', 2004, 'Brad Bird', 'A family of undercover superheroes, while trying to live the quiet suburban life, are forced into action to save the world.', 'https://youtu.be/eZbzbC9285I', 'https://upload.wikimedia.org/wikipedia/en/e/ec/The_Incredibles.jpg', 8.0),
('Finding Nemo', 2003, 'Andrew Stanton', 'After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.', 'https://youtu.be/2zLkasScy7A', 'https://upload.wikimedia.org/wikipedia/en/2/29/Finding_Nemo.jpg', 8.2),
('Ratatouille', 2007, 'Brad Bird', 'A rat who can cook makes an unusual alliance with a young kitchen worker at a famous restaurant.', 'https://youtu.be/NgsQ8mVkN8w', 'https://upload.wikimedia.org/wikipedia/en/5/50/RatatouillePoster.jpg', 8.1),
('Zootopia', 2016, 'Byron Howard, Rich Moore', 'In a city of anthropomorphic animals, a rookie bunny cop and a cynical con artist fox must work together to uncover a conspiracy.', 'https://youtu.be/jWM0ct-OLsM', 'https://upload.wikimedia.org/wikipedia/en/e/ea/Zootopia.jpg', 8.0),
('Frozen', 2013, 'Chris Buck, Jennifer Lee', 'When the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister Anna teams up with a mountain man, his playful reindeer, and a snowman to change the weather condition.', 'https://youtu.be/TbQm5doF_Uc', 'https://upload.wikimedia.org/wikipedia/en/0/05/Frozen_%282013_film%29_poster.jpg', 7.4),
('Spider-Man: Into the Spider-Verse', 2018, 'Bob Persichetti, Peter Ramsey, Rodney Rothman', 'Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.', 'https://youtu.be/g4Hbz2jLxvQ', 'https://upload.wikimedia.org/wikipedia/en/f/fa/Spider-Man_Into_the_Spider-Verse_poster.png', 8.4),
('The Social Network', 2010, 'David Fincher', 'As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea, and by the co-founder who was later squeezed out of the business.', 'https://youtu.be/lB95KLmpLR4', 'https://upload.wikimedia.org/wikipedia/en/7/7a/Social_network_film_poster.jpg', 7.7),
('La La Land', 2016, 'Damien Chazelle', 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.', 'https://youtu.be/0pdqf4P9MB8', 'https://upload.wikimedia.org/wikipedia/en/a/ab/La_La_Land_%28film%29.png', 8.0),
('The Shape of Water', 2017, 'Guillermo del Toro', 'At a top secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.', 'https://youtu.be/XFYWazblaUA', 'https://upload.wikimedia.org/wikipedia/en/3/37/The_Shape_of_Water_%28film%29.png', 7.3),
('Get Out', 2017, 'Jordan Peele', 'A young African-American visits his white girlfriend''s parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.', 'https://youtu.be/DzfpyUB60YY', 'https://upload.wikimedia.org/wikipedia/en/a/a3/Get_Out_poster.png', 7.7),
('Hereditary', 2018, 'Ari Aster', 'After the family matriarch passes away, a grieving family is haunted by tragic and disturbing occurrences, and begin to unravel dark secrets.', 'https://youtu.be/V6wWKNij_1M', 'https://upload.wikimedia.org/wikipedia/en/1/1f/Hereditary_%28film%29.jpg', 7.3),
('A Quiet Place', 2018, 'John Krasinski', 'In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.', 'https://youtu.be/WR7cc5t7tv8', 'https://upload.wikimedia.org/wikipedia/en/a/a0/A_Quiet_Place_film_poster.png', 7.5),
('Mad Max: Fury Road', 2015, 'George Miller', 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.', 'https://youtu.be/hEJnMQG9ev8', 'https://upload.wikimedia.org/wikipedia/en/6/6e/Mad_Max_Fury_Road.jpg', 8.1),
('Blade Runner 2049', 2017, 'Denis Villeneuve', 'A young blade runner''s discovery of a long-buried secret leads him to track down former blade runner Rick Deckard, who''s been missing for thirty years.', 'https://youtu.be/gCcx85zbxz4', 'https://upload.wikimedia.org/wikipedia/en/2/27/Blade_Runner_2049_poster.png', 8.0);

-- Insert additional genres if needed
INSERT INTO genres (genre_name) VALUES
('Biography'),
('War'),
('Musical'),
('Western'),
('Film-Noir'),
('Family'),
('History'),
('Sport'),
('Documentary'),
('Short'),
('Fantasy'),
('Superhero');

-- Insert additional actors (total 60 actors)
INSERT INTO actors (actor_name) VALUES
('Robert De Niro'),
('Jack Nicholson'),
('Anthony Hopkins'),
('Brad Pitt'),
('Edward Norton'),
('Joaquin Phoenix'),
('Gary Oldman'),
('Kevin Spacey'),
('Russell Crowe'),
('Matt Damon'),
('Mark Wahlberg'),
('Will Smith'),
('Denzel Washington'),
('Tom Cruise'),
('Harrison Ford'),
('Johnny Depp'),
('Daniel Day-Lewis'),
('Sean Penn'),
('Philip Seymour Hoffman'),
('Javier Bardem'),
('Christoph Waltz'),
('Ryan Gosling'),
('Emma Stone'),
('Ellen Page'),
('Michael B. Jordan'),
('Chadwick Boseman'),
('Brie Larson'),
('Scarlett Johansson'),
('Chris Evans'),
('Robert Downey Jr.'),
('Chris Hemsworth'),
('Mark Ruffalo'),
('Jeremy Renner'),
('Josh Brolin'),
('Benedict Cumberbatch'),
('Tom Hardy'),
('Zoe Saldana'),
('Vin Diesel'),
('Paul Rudd'),
('Chiwetel Ejiofor'),
('Idris Elba'),
('Michael Fassbender'),
('James McAvoy'),
('Patrick Stewart'),
('Ian McKellen'),
('Hugh Jackman'),
('Ryan Reynolds'),
('Jake Gyllenhaal'),
('Andrew Garfield'),
('Tobey Maguire'),
('Anne Hathaway'),
('Natalie Portman'),
('Jennifer Lawrence'),
('Amy Adams'),
('Cate Blanchett'),
('Meryl Streep'),
('Julianne Moore'),
('Nicole Kidman'),
('Charlize Theron'),
('Margot Robbie'),
('Gal Gadot');

-- Movies with genres (for all 50 movies)
INSERT INTO movies_with_genres (movie_id, genre_id) VALUES
(1,1), (2,1), (2,2), (3,3), (3,1), (3,2), (4,2), (4,1), (4,8), (5,1), (5,2), (5,4),
(6,1), (6,11), (7,5), (7,3), (7,12), (8,5), (8,3), (9,1), (9,2), (10,1), (10,4), (10,12),
(11,1), (11,8), (12,5), (12,1), (12,6), (13,6), (13,7), (13,1), (14,6), (14,7), (14,1),
(15,1), (15,12), (16,2), (16,4), (16,12), (17,2), (17,4), (17,12), (18,1), (18,2), (18,4),
(19,1), (19,17), (20,1), (20,17), (21,1), (21,17), (21,6), (22,2), (22,1), (22,4), (23,1), (23,12),
(24,1), (24,8), (25,1), (25,8), (26,1), (26,8), (27,1), (27,8), (28,3), (28,5), (28,6), (29,3), (29,5), (29,6),
(30,3), (30,1), (30,6), (31,1), (31,17), (31,8), (32,1), (32,8), (32,11), (33,9), (33,6), (33,7), (34,9), (34,6), (34,11),
(35,9), (35,6), (35,22), (36,9), (36,6), (36,22), (37,9), (37,6), (37,22), (38,9), (38,6), (38,22), (39,9), (39,6), (39,22),
(40,9), (40,6), (40,22), (41,9), (41,6), (41,22), (42,9), (42,6), (42,22), (43,9), (43,6), (43,22), (44,9), (44,6), (44,22),
(45,9), (45,6), (45,22), (46,1), (46,23), (47,1), (47,8), (47,11), (48,1), (48,12), (48,5), (49,10), (49,4), (49,12), (50,10), (50,4), (50,5);

-- Movies with actors (for all 50 movies with 2-5 actors each)
INSERT INTO movies_with_actors (movie_id, actor_id) VALUES
(1,1), (1,2), (2,3), (2,4), (3,5), (3,6), (4,7), (4,8), (4,9), (5,10), (5,11),
(6,12), (7,13), (7,14), (8,15), (9,16), (9,17), (10,18), (10,19), (11,20), (12,21), (12,22),
(13,23), (13,24), (14,23), (14,24), (15,12), (15,25), (16,26), (16,27), (17,28), (17,29), (18,30), (18,31),
(19,32), (19,33), (20,34), (21,35), (21,36), (22,37), (22,38), (23,39), (23,40), (24,41), (24,42), (25,43), (25,44),
(26,45), (26,46), (27,47), (27,48), (28,49), (28,50), (29,51), (29,52), (30,53), (30,54), (31,55), (31,56),
(32,57), (32,58), (33,59), (33,60), (34,61), (34,62), (35,63), (35,64), (36,65), (36,66), (37,67), (37,68),
(38,69), (38,70), (39,71), (39,72), (40,73), (40,74), (41,75), (41,76), (42,77), (42,78), (43,79), (43,80),
(44,81), (44,82), (45,83), (45,84), (46,85), (46,86), (47,87), (47,88), (48,89), (48,90), (49,91), (49,92),
(50,93), (50,94);